# Generated by Django 4.2.8 on 2024-03-15 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chack_in_date', models.DateField(auto_now=True, verbose_name='In date')),
                ('chack_on_date', models.DateField(verbose_name='ON DATE')),
                ('is_paid', models.BooleanField(verbose_name='Paid id')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='guest')),
                ('rooms', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='room.room', verbose_name='room')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
