# Generated by Django 4.2.8 on 2024-03-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Host name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address of  the host')),
                ('city', models.TextField(verbose_name='city')),
                ('country', models.TextField(verbose_name='country')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='rating')),
                ('image', models.ImageField(upload_to='hotels-img/%Y/%m/%d', verbose_name='Img')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
    ]
